network:
  version: 2
  ethernets:
     enp0s3:
        dhcp4: false
        addresses: [10.1.20.60/24]
        gateway4: 10.1.20.10
        nameservers:
          addresses: [10.1.20.10, 1.1.1.1, 8.8.8.8]
